# -*- coding: utf-8 -*-
"""Upliance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IkeGrDF97yZ_dQX7HrfM1n-iySPuNBr
"""

import numpy as np
import pandas as pd
file_path = '/content/Assignment.xlsx'
df = pd.read_excel('/content/Assignment.xlsx', sheet_name = None)

print(df.keys())

user_details = df['UserDetails.csv']
cooking_sessions = df['CookingSessions.csv']
order_details = df['OrderDetails.csv']

print(user_details)
print("*"*100)
print(cooking_sessions)
print("*"*100)
print(order_details)

cooking_sessions['Session Start'] = pd.to_datetime(cooking_sessions['Session Start'], errors='coerce')
cooking_sessions['Session End'] = pd.to_datetime(cooking_sessions['Session End'], errors='coerce')

order_details['Rating'] = order_details['Rating'].fillna(order_details['Rating'].mean())

order_details['Order Date'] = pd.to_datetime(order_details['Order Date'])

print(user_details)
print("*"*100)
print(cooking_sessions)
print("*"*100)
print(order_details)

"""#Merging Datasets

"""

Merged_data = pd.merge(cooking_sessions,user_details, on = 'User ID', how = 'left')

Dataframe = pd.merge(Merged_data, order_details, on=['User ID', 'Session ID'], how = 'left')

"""Relation Between Cooking Sessions and User Orders"""

orders_per_session = Dataframe.groupby('Session ID')['Order ID'].count().reset_index()
orders_per_session = orders_per_session.rename(columns={'Order ID': 'Order Count'})

average_session_rating = Dataframe.groupby('Session ID')['Rating'].mean().reset_index()
average_session_rating = average_session_rating.rename(columns={'Rating':'Average Session Rating'})

Dataframe = pd.merge(Dataframe, orders_per_session, on='Session ID',how='left')
Dataframe = pd.merge(Dataframe, average_session_rating, on= 'Session ID', how = 'left')
print(Dataframe[['Session ID','Order Count','Average Session Rating']].head())

# print(Dataframe.describe())
popular_dishes = Dataframe.groupby('Dish Name_x')['Order ID'].count().reset_index()
popular_dishes = popular_dishes.sort_values(by = 'Order ID',ascending= False)
print(popular_dishes.head(10))

"""Demographic factors that influence user behavior

"""

age_group_orders = Dataframe.groupby('Age')['Order ID'].count().reset_index()
age_group_orders = age_group_orders.rename(columns={'Order ID': 'Order Count'})

location_orders = Dataframe.groupby('Location')['Order ID'].count().reset_index()
location_orders = location_orders.rename(columns={'Order ID':'Order Count'})

favorite_meal_orders = Dataframe.groupby('Favorite Meal')['Order ID'].count().reset_index()
favorite_meal_orders = favorite_meal_orders.rename(columns={'Order ID': 'Order Count'})

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,6))
sns.barplot(data=popular_dishes.head(10), x='Dish Name_x', y='Order ID')
plt.xticks(rotation = 45, ha='right')
plt.title('Top 10 Most Popular Dishes')
plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(data=age_group_orders, x='Age', y='Order Count')
plt.title('Orders by Age Group')
plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(data=location_orders, x='Location', y='Order Count')
plt.title('Orders by Location')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(data=favorite_meal_orders, x='Favorite Meal', y='Order Count')
plt.title('Orders by Favorite Meal')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(age_favorite_meal, annot = True, cmap='coolwarm')
plt.title('User Behavior: age vs Favorite Meal')
plt.show()

meal_order.set_index('Meal Type_x')[['order_count', 'total_amount']].plot(kind='bar',figsize = (10,6))
plt.title('Meal Type Analysis: Order Count & Total Amount')
plt.xticks(rotation = 0)
plt.ylabel('count/ Amount (USD)')
plt.show()